import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import { Box, Container, Typography } from '@mui/material'

export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Box sx={{ border: '1px dashed red', width: '100%', height: '100%' }}>
          <Typography variant='h1'>Hello World</Typography>
        </Box> */}
        <Box sx={{ height: '100vh', width: '100%', border: '1px dashed red' }}>
          <Layout />
        </Box>
      </main>
    </div>
  )
}
