import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box } from '@mui/material'
import { app } from '../App/Source/app'
import CanvaAppComponent from '../components/CanvaApp'

export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ border: 'solid red', width: '100vw', height: '100vh' }}>
        <CanvaAppComponent app={app} />
        {/* <CanvaAppComponent app={app} /> */}
        {/* <h1>witam</h1> */}
      </main>
    </div>
  )
}
